<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <AssemblyName>VGBBoardAlways</AssemblyName>
    <Product>Board Always</Product>
    <Version>0.4.1</Version>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <RootNamespace>VGBBoardAlways</RootNamespace>
    <RestoreAdditionalProjectSources>
      https://api.nuget.org/v3/index.json;
      https://nuget.bepinex.dev/v3/index.json;
      https://nuget.samboy.dev/v3/index.json
    </RestoreAdditionalProjectSources>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BepInEx.Analyzers" Version="1.*" PrivateAssets="all" />
    <PackageReference Include="BepInEx.Core" Version="5.*" IncludeAssets="compile" />
    <PackageReference Include="BepInEx.PluginInfoProps" Version="2.*" />

  </ItemGroup>

  <ItemGroup>
    <!-- Unity is needed only to compile BepInEx's BaseUnityPlugin entry point. -->
    <Reference Include="UnityEngine">
      <HintPath>lib/UnityEngine.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>lib/UnityEngine.CoreModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="VGModAPI.Abstractions">
      <HintPath>lib/VGModAPI.Abstractions.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

</Project>
